spring:
  application:
    name: configclient
  cloud:
    config:
      label: master
      profile: test
      uri: http://localhost:8888/
server:
  port: 6666
management:  #actuator
  server:
    port: 1111
  endpoints:
    web:
      base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
